# Generated by Django 4.2.7 on 2025-10-21 15:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la bebida (ej. Agua, Café, Té, etc.)', max_length=100, unique=True, verbose_name='Nombre de la bebida')),
                ('factor_hidratacion', models.FloatField(default=1.0, help_text='Factor que indica qué tan hidratante es la bebida (0.0-2.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Factor de hidratación')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la bebida', null=True, verbose_name='Descripción')),
                ('es_agua', models.BooleanField(default=False, help_text='Indica si esta bebida es agua pura', verbose_name='Es agua')),
                ('calorias_por_ml', models.FloatField(default=0.0, help_text='Calorías por mililitro de la bebida', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Calorías por ml')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la bebida está disponible para seleccionar', verbose_name='Activa')),
                ('es_premium', models.BooleanField(default=False, help_text='Indica si la bebida es exclusiva para usuarios premium', verbose_name='Es Premium')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Bebida',
                'verbose_name_plural': 'Bebidas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recipiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre personalizado del recipiente (ej. Botella grande, Vaso)', max_length=100, verbose_name='Nombre del recipiente')),
                ('cantidad_ml', models.PositiveIntegerField(help_text='Capacidad del recipiente en mililitros', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='Capacidad (ml)')),
                ('color', models.CharField(default='#3B82F6', help_text='Color del recipiente en formato hexadecimal', max_length=7, verbose_name='Color')),
                ('icono', models.CharField(default='bottle', help_text='Nombre del icono para representar el recipiente', max_length=50, verbose_name='Icono')),
                ('es_favorito', models.BooleanField(default=False, help_text='Indica si este recipiente es uno de los favoritos del usuario', verbose_name='Es favorito')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipientes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Recipiente',
                'verbose_name_plural': 'Recipientes',
                'ordering': ['-es_favorito', 'nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(help_text='Hora del día para el recordatorio (HH:MM)', verbose_name='Hora del recordatorio')),
                ('mensaje', models.CharField(blank=True, help_text='Mensaje opcional para el recordatorio', max_length=200, null=True, verbose_name='Mensaje personalizado')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el recordatorio está activo', verbose_name='Activo')),
                ('dias_semana', models.JSONField(default=list, help_text='Lista de días de la semana (0=Lunes, 6=Domingo)', verbose_name='Días de la semana')),
                ('tipo_recordatorio', models.CharField(choices=[('agua', 'Recordatorio de agua'), ('meta', 'Recordatorio de meta'), ('personalizado', 'Recordatorio personalizado')], default='agua', help_text='Tipo de recordatorio', max_length=20, verbose_name='Tipo de recordatorio')),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('dias_laborales', 'Días laborales'), ('fines_semana', 'Fines de semana'), ('personalizado', 'Personalizado')], default='diario', help_text='Frecuencia del recordatorio', max_length=20, verbose_name='Frecuencia')),
                ('sonido', models.CharField(default='default', help_text='Sonido del recordatorio', max_length=50, verbose_name='Sonido')),
                ('vibracion', models.BooleanField(default=True, help_text='Activar vibración en el recordatorio', verbose_name='Vibración')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('ultimo_enviado', models.DateTimeField(blank=True, help_text='Fecha y hora del último envío del recordatorio', null=True, verbose_name='Último enviado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['hora'],
                'unique_together': {('usuario', 'hora', 'tipo_recordatorio')},
            },
        ),
        migrations.CreateModel(
            name='MetaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de la meta diaria', verbose_name='Fecha')),
                ('meta_ml', models.PositiveIntegerField(help_text='Meta de hidratación en mililitros para este día', verbose_name='Meta (ml)')),
                ('consumido_ml', models.PositiveIntegerField(default=0, help_text='Cantidad total consumida en mililitros', verbose_name='Consumido (ml)')),
                ('hidratacion_efectiva_ml', models.PositiveIntegerField(default=0, help_text='Cantidad total de hidratación efectiva en mililitros', verbose_name='Hidratación efectiva (ml)')),
                ('completada', models.BooleanField(default=False, help_text='Indica si se alcanzó la meta del día', verbose_name='Completada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_diarias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Meta Diaria',
                'verbose_name_plural': 'Metas Diarias',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ml', models.PositiveIntegerField(help_text='Cantidad consumida en mililitros', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='Cantidad (ml)')),
                ('cantidad_hidratacion_efectiva', models.PositiveIntegerField(help_text='Cantidad de hidratación efectiva considerando el factor de la bebida', verbose_name='Hidratación efectiva (ml)')),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora del consumo', verbose_name='Fecha y hora')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el consumo', null=True, verbose_name='Notas')),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación donde se realizó el consumo', max_length=200, null=True, verbose_name='Ubicación')),
                ('temperatura_ambiente', models.FloatField(blank=True, help_text='Temperatura ambiente al momento del consumo', null=True, verbose_name='Temperatura ambiente (°C)')),
                ('nivel_sed', models.PositiveIntegerField(blank=True, choices=[(1, 'Muy poca sed'), (2, 'Poca sed'), (3, 'Sed normal'), (4, 'Mucha sed'), (5, 'Muy sediento')], help_text='Nivel de sed antes del consumo', null=True, verbose_name='Nivel de sed')),
                ('estado_animo', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('terrible', 'Terrible')], help_text='Estado de ánimo al momento del consumo', max_length=20, null=True, verbose_name='Estado de ánimo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='consumos.bebida', verbose_name='Bebida')),
                ('recipiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='consumos.recipiente', verbose_name='Recipiente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Consumo',
                'verbose_name_plural': 'Consumos',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', 'fecha_hora'], name='consumos_co_usuario_7e4c31_idx'), models.Index(fields=['fecha_hora'], name='consumos_co_fecha_h_eb0d63_idx')],
            },
        ),
    ]
