# Generated by Django 5.2.7 on 2025-11-11 00:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('correr', 'Correr / Ciclismo'), ('gimnasio', 'Gimnasio / Pesas'), ('deportes', 'Deportes'), ('caminata', 'Caminata rápida / Yoga dinámico')], help_text='Tipo de actividad física realizada', max_length=20, verbose_name='Tipo de actividad')),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Duración de la actividad en minutos', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Duración (minutos)')),
                ('intensidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], help_text='Intensidad de la actividad (Baja, Media, Alta)', max_length=10, verbose_name='Intensidad')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se realizó la actividad', verbose_name='Fecha y hora')),
                ('pse_calculado', models.PositiveIntegerField(help_text='Pérdida de Sudor Estimada calculada en mililitros', verbose_name='PSE Calculado (ml)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro de la actividad', verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de actualización')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la actividad', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', 'fecha_hora'], name='actividades_usuario_21db20_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='actividades_usuario_cff8e2_idx')],
            },
        ),
    ]
