# Generated by Django 4.2.7 on 2025-10-21 15:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Dirección de correo electrónico única del usuario', max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('peso', models.FloatField(blank=True, help_text='Peso del usuario en kilogramos (20-300 kg)', null=True, validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(300.0)], verbose_name='Peso (kg)')),
                ('edad', models.PositiveIntegerField(blank=True, help_text='Edad del usuario en años (1-120 años)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Edad (años)')),
                ('es_premium', models.BooleanField(default=False, help_text='Indica si el usuario tiene una suscripción premium', verbose_name='Usuario Premium')),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del usuario', null=True, verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], help_text='Género del usuario', max_length=10, null=True, verbose_name='Género')),
                ('nivel_actividad', models.CharField(choices=[('sedentario', 'Sedentario'), ('ligero', 'Actividad ligera'), ('moderado', 'Actividad moderada'), ('intenso', 'Actividad intensa'), ('muy_intenso', 'Actividad muy intensa')], default='moderado', help_text='Nivel de actividad física del usuario', max_length=20, verbose_name='Nivel de actividad')),
                ('meta_diaria_ml', models.PositiveIntegerField(default=2000, help_text='Meta de hidratación diaria en mililitros', validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(10000)], verbose_name='Meta diaria (ml)')),
                ('recordar_notificaciones', models.BooleanField(default=True, help_text='Indica si el usuario desea recibir recordatorios de hidratación', verbose_name='Recordar notificaciones')),
                ('hora_inicio', models.TimeField(default='08:00', help_text='Hora de inicio para los recordatorios de hidratación', verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(default='22:00', help_text='Hora de fin para los recordatorios de hidratación', verbose_name='Hora de fin')),
                ('intervalo_notificaciones', models.PositiveIntegerField(default=60, help_text='Intervalo en minutos entre recordatorios de hidratación', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)], verbose_name='Intervalo de notificaciones (min)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la cuenta', verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del perfil', verbose_name='Fecha de actualización')),
                ('ultimo_acceso', models.DateTimeField(blank=True, help_text='Fecha y hora del último acceso del usuario', null=True, verbose_name='Último acceso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_creacion'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
