# Generated by Django 5.2.7 on 2025-11-10 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='es_fragil_o_insuficiencia_cardiaca',
            field=models.BooleanField(blank=True, default=False, help_text='Indica si la persona es frágil o tiene insuficiencia cardíaca (solo para mayores de 65 años)', null=True, verbose_name='Persona frágil o con insuficiencia cardíaca'),
        ),
        migrations.AlterField(
            model_name='user',
            name='peso',
            field=models.FloatField(blank=True, help_text='Peso del usuario en kilogramos', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(500.0)], verbose_name='Peso (kg)'),
        ),
    ]
