# Generated by Django 5.2.7 on 2025-11-13 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_make_peso_fecha_nacimiento_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bebida', 'Bebida'), ('actividad', 'Actividad')], help_text='Tipo de sugerencia (bebida o actividad)', max_length=20, verbose_name='Tipo de sugerencia')),
                ('nombre', models.CharField(help_text='Nombre de la bebida o actividad sugerida', max_length=200, verbose_name='Nombre')),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios adicionales o ingredientes (opcional)', null=True, verbose_name='Comentarios')),
                ('intensidad_estimada', models.CharField(blank=True, choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], help_text='Intensidad estimada (solo para actividades)', max_length=10, null=True, verbose_name='Intensidad estimada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la sugerencia', verbose_name='Fecha de creación')),
                ('procesada', models.BooleanField(default=False, help_text='Indica si la sugerencia ha sido procesada por un administrador', verbose_name='Procesada')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la sugerencia', on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sugerencia',
                'verbose_name_plural': 'Sugerencias',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'tipo'], name='users_suger_usuario_33c6eb_idx'), models.Index(fields=['procesada'], name='users_suger_procesa_9f01bd_idx')],
            },
        ),
    ]
