# Generated by Django 5.2.7 on 2025-11-13 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sugerencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('idea_sugerencia', 'Idea/Sugerencia'), ('reporte_error', 'Reporte de Error'), ('pregunta_general', 'Pregunta General')], help_text='Tipo de feedback (idea, error, pregunta)', max_length=30, verbose_name='Tipo de feedback')),
                ('mensaje', models.TextField(help_text='Mensaje del usuario', verbose_name='Mensaje')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del feedback', verbose_name='Fecha de creación')),
                ('procesado', models.BooleanField(default=False, help_text='Indica si el feedback ha sido procesado por el equipo', verbose_name='Procesado')),
                ('usuario', models.ForeignKey(help_text='Usuario que envió el feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'tipo'], name='users_feedb_usuario_fc67a5_idx'), models.Index(fields=['procesado'], name='users_feedb_procesa_145838_idx')],
            },
        ),
    ]
