# Generated by Django 5.2.7 on 2025-11-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codigo_referido',
            field=models.CharField(blank=True, help_text='Código único del usuario para referir a otros', max_length=20, null=True, unique=True, verbose_name='Código de referido'),
        ),
        migrations.AddField(
            model_name='user',
            name='codigo_referido_usado',
            field=models.CharField(blank=True, help_text='Código de referido que el usuario usó al registrarse', max_length=20, null=True, verbose_name='Código de referido usado'),
        ),
        migrations.AddField(
            model_name='user',
            name='recompensas_reclamadas',
            field=models.PositiveIntegerField(default=0, help_text='Número de recompensas de referidos que el usuario ha reclamado', verbose_name='Recompensas reclamadas'),
        ),
        migrations.AddField(
            model_name='user',
            name='referidos_verificados',
            field=models.PositiveIntegerField(default=0, help_text='Número de referidos que se han registrado y verificado con este código', verbose_name='Referidos verificados'),
        ),
    ]
