# Generated by Django 5.2.7 on 2025-11-14 14:10

from django.db import migrations
import secrets
import string


def generar_codigo_referido():
    """Genera un código de referido único."""
    caracteres = string.ascii_uppercase + string.digits
    codigo_sufijo = ''.join(secrets.choice(caracteres) for _ in range(8))
    return f"TOMA_{codigo_sufijo}"


def generar_codigos_para_usuarios_existentes(apps, schema_editor):
    """Genera códigos de referido para usuarios existentes que no tengan uno."""
    User = apps.get_model('users', 'User')
    
    usuarios_sin_codigo = User.objects.filter(codigo_referido__isnull=True) | User.objects.filter(codigo_referido='')
    
    codigos_existentes = set(User.objects.exclude(codigo_referido__isnull=True).exclude(codigo_referido='').values_list('codigo_referido', flat=True))
    
    for usuario in usuarios_sin_codigo:
        # Generar código único
        while True:
            codigo = generar_codigo_referido()
            if codigo not in codigos_existentes:
                usuario.codigo_referido = codigo
                codigos_existentes.add(codigo)
                usuario.save(update_fields=['codigo_referido'])
                break


def reverse_generar_codigos(apps, schema_editor):
    """No hacer nada al revertir la migración."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_codigo_referido_user_codigo_referido_usado_and_more'),
    ]

    operations = [
        migrations.RunPython(
            generar_codigos_para_usuarios_existentes,
            reverse_generar_codigos
        ),
    ]
